### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by austinhuang0131** [trembacz/diff-checker#3]
A CSS toggle switch? Since macOS has dark mode and it would be nice if the app can be consistent...

No, I don't need dark mode detection, just a button is enough.

**Comment by trembacz** [comment]
Good idea @austinhuang0131, I will add it when I have some spare time.

**Comment by trembacz** [comment]
@austinhuang0131, 

It's almost done! The new version will be published shortly (the app should update automatically when the new version will be available).

The button to switch the theme has been added, now the selected theme is saved in the config, and it is used in the next app use.

System theme detection is already in place, but it's not enabled in this version. It will be enabled probably in the next version as I need to add an extra button somewhere to give users the choice of using OS theme or manually selected.

![dm](https://user-images.githubusercontent.com/4508357/111110194-6309bc80-855c-11eb-8bec-651cd3480809.PNG)

**Comment by trembacz** [comment]
@austinhuang0131, looks like Apple changed something with their policy for the code signing (for applications) In short, my certificate is not valid anymore and there are some problems with application auto-update (with a new certificate). The new version will be available when I fix the certificate problem. If you want the new version but not signed, let me know I can send you a link.
